type: { { cookiecutter.entityType } }

title: { { cookiecutter.entityTitle } }

description: { { cookiecutter.entityDescription } }

relatedSystem: { { cookiecutter.entityRelatedSystem } }

jenkins:
  job: <JENKINS_SERVICE_NAME>
